title: Writings
description: >
    &copy; 2018 Andrew McAuley
    This page is licensed under the terms of [CC BY-SA 4.0 license](http://creativecommons.org/licenses/by-sa/4.0/)
    
author: Andrew McAuley
theme: minima
plugins:
 - jekyll-sitemap

github_username: am01264
show_excerpts: true
