title: The Lense
description: Clarifying the chaos of life through writing, and rambling.

author: Andrew McAuley
theme: minima
plugins:
 - jekyll-sitemap
 - jekyll-feed

github_username: am01264
show_excerpts: true

