title: The Lense
description: Clarifying the chaos of life through writing, and rambling.

author: Andrew McAuley

# theme: minima
remote_theme: broccolini/swiss

plugins:
 - jekyll-sitemap
 - jekyll-feed

# Undocumented `broccolini/swiss` feature, may fail in future update
social_link: dot

show_excerpts: true

